__file__: specs/pde_convection/exp_template.yaml
config/__spec__/algorithm:
    __call__: theory2practice.algorithms.PinnAlgorithm
    data_loader_kwargs:
        batch_size:
            eval: int(np.maximum(spec.config.n_samples, 1))
        shuffle: false
    grid:
        __call__: theory2practice.utils.TensorGrid
        nx:
            grid_search:
            - 256
        nt:
            grid_search:
            - 100
    epochs_per_iteration: 100
    loss:
        __call__: theory2practice.utils.PinnLoss
        loss_factor: 1
        loss_style: mean
    n_f:
        grid_search:
            - 100
    model:
        __call__: theory2practice.algorithms.FeedForward
        activation:
            __call__: torch.nn.Tanh
        depth: 5
        input_dim: 2
        width: 50
    optimizer_factory:
        __import__: torch.optim.Adam
    optimizer_kwargs:
        lr: 1
config/__spec__/wandb/group: exp_1
name: exp_1
